In [1]:
import numpy as np
import pandas as pd

In [27]:
l = [[1, 1, 2], [3, 4, 2], [3, 5, 1]]
s = pd.Series(l)
a = np.asarray(l, dtype=np.float64)

a, a.T

for i, x in enumerate(a.T): print (i, x)

0 [1. 3. 3.]
1 [1. 4. 5.]
2 [2. 2. 1.]


In [6]:
s.value_counts(normalize=True).to_dict()

{1: 0.25, 2: 0.25, 3: 0.25, 4: 0.125, 5: 0.125}

In [14]:
u, c = np.unique(a, return_counts=True)
d = dict(zip(u, c / len(a)))

d

{np.float64(1.0): np.float64(0.25),
 np.float64(2.0): np.float64(0.25),
 np.float64(3.0): np.float64(0.25),
 np.float64(4.0): np.float64(0.125),
 np.float64(5.0): np.float64(0.125)}

In [41]:
def split(X, feature, threshold):
        left = np.where(X[:, feature] <= threshold)[0]
        right = np.where(X[:, feature] > threshold)[0]

        return left, right

left, right = (split(a, 1, 4))
print(a)
print(left, right)
a1 = a[left]
a2 = a[right]
print(a1, a2, sep='\n')

[[1. 1. 2.]
 [3. 4. 2.]
 [3. 5. 1.]]
[0 1] [2]
[[1. 1. 2.]
 [3. 4. 2.]]
[[3. 5. 1.]]
